version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo Running tests...
      - python -m pytest
      - echo Running pylint code analysis...
      - pylint --disable=C0111,C0103,C0303,W0613,R0903,E1101 recipes/*.py accounts/*.py
  
  build:
    commands:
      - echo Running SonarQube analysis...
      - echo "SonarQube analysis would be performed here in a real environment"
      - echo "Checking security vulnerabilities..."
      
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'